const STORAGE_KEY = "ai_learning_tool_system";

let state = JSON.parse(localStorage.getItem(STORAGE_KEY)) || {
  pretest: null,
  posttest: null,
  exploredTools: [],
  recommendation: null,
  quiz: null,
  promptPractice: null
};

const aiTools = [
  { id: "chatgpt", name: "ChatGPT", category: "Writing / Research", description: "AI assistant for writing, brainstorming, summarization, and explanations." },
  { id: "grammarly", name: "Grammarly", category: "Writing Support", description: "AI tool for grammar checking, clarity, and proofreading." },
  { id: "copilot", name: "GitHub Copilot", category: "Programming", description: "AI coding assistant for programming support and debugging." },
  { id: "canva", name: "Canva AI", category: "Presentation / Design", description: "AI-supported visual presentation and design tool." },
  { id: "gemini", name: "Google Gemini", category: "Research / Brainstorming", description: "AI assistant for idea generation and research support." },
  { id: "notebooklm", name: "NotebookLM", category: "Reading / Notes", description: "AI tool for summarizing uploaded notes and readings." }
];

const surveyConfig = [
  {
    title: "Awareness / Prior Knowledge",
    items: [
      "I am aware of AI tools that can be used for learning.",
      "I know the different types of AI tools available for students.",
      "I understand how AI tools can support academic tasks.",
      "I know where to access AI tools for learning.",
      "I am familiar with the ethical use of AI tools in education."
    ]
  },
  {
    title: "Perceived Usefulness",
    items: [
      "AI tools can improve my learning performance.",
      "AI tools help me accomplish academic tasks more efficiently.",
      "AI tools make studying easier.",
      "AI tools are useful for completing school requirements.",
      "AI tools can help me understand lessons better."
    ]
  },
  {
    title: "Perceived Ease of Use",
    items: [
      "Learning how to use AI tools is easy for me.",
      "AI tools are clear and understandable.",
      "I find AI tools easy to operate.",
      "Using AI tools does not require much effort.",
      "I can easily learn new AI tools when needed."
    ]
  },
  {
    title: "Trust / Credibility / Privacy Concerns",
    items: [
      "I trust the information generated by AI tools.",
      "AI tools provide reliable outputs for learning.",
      "I am confident that I can verify AI-generated information.",
      "I am concerned about privacy when using AI tools.",
      "I believe AI tools should be used responsibly in academic work."
    ]
  },
  {
    title: "AI Self-Efficacy",
    items: [
      "I am confident in my ability to use AI tools.",
      "I can use AI tools without much assistance.",
      "I can learn new AI tools independently.",
      "I can apply AI tools effectively in my studies.",
      "I can solve basic problems when using AI tools."
    ]
  },
  {
    title: "Subjective Norms",
    items: [
      "My classmates encourage the use of AI tools for learning.",
      "My instructors support the responsible use of AI tools.",
      "People important to me think I should use AI tools for learning.",
      "AI tool usage is common among my peers.",
      "There is social encouragement to use AI tools academically."
    ]
  },
  {
    title: "Perceived Behavioral Control",
    items: [
      "I have access to the devices needed to use AI tools.",
      "I have internet access to use AI learning tools.",
      "I have enough time to explore and use AI tools.",
      "I have the ability to learn how to use AI tools.",
      "I have the resources needed to use AI tools for learning."
    ]
  },
  {
    title: "Behavioral Intention",
    items: [
      "I intend to use AI tools for my studies.",
      "I plan to use AI tools for future academic tasks.",
      "I am willing to use AI tools responsibly.",
      "I will recommend AI learning tools to other students.",
      "I expect to continue using AI tools for learning."
    ]
  },
  {
    title: "Actual Usage / Adoption",
    items: [
      "I frequently use AI tools for academic tasks.",
      "I use AI tools for writing or editing school work.",
      "I use AI tools for research or summarization.",
      "I use AI tools for studying or reviewing lessons.",
      "I use more than one AI tool for learning."
    ]
  }
];

const recommendationMap = {
  writing: {
    tools: ["ChatGPT", "Grammarly"],
    reason: "These tools are useful for essay writing, outlining, grammar checking, and improving clarity."
  },
  research: {
    tools: ["ChatGPT", "Google Gemini", "NotebookLM"],
    reason: "These tools are useful for summarizing readings, explaining concepts, and supporting research work."
  },
  presentation: {
    tools: ["Canva AI", "ChatGPT"],
    reason: "These tools are useful for creating presentation content, visuals, and slide outlines."
  },
  coding: {
    tools: ["GitHub Copilot", "ChatGPT"],
    reason: "These tools are useful for coding support, debugging, and understanding programming logic."
  },
  study: {
    tools: ["ChatGPT", "NotebookLM"],
    reason: "These tools are useful for creating reviewers, summaries, flashcards, and study guides."
  },
  brainstorm: {
    tools: ["ChatGPT", "Google Gemini"],
    reason: "These tools are useful for generating ideas, organizing concepts, and developing outlines."
  }
};

const quizQuestions = [
  {
    question: "Why is verifying AI-generated information important?",
    options: [
      "AI is always accurate.",
      "AI may generate inaccurate or misleading information.",
      "Verification is unnecessary.",
      "AI tools cannot be used in education."
    ],
    answer: 1
  },
  {
    question: "Which is responsible AI usage?",
    options: [
      "Submitting raw AI outputs as final work.",
      "Using AI ethically and verifying outputs.",
      "Copy-pasting without editing.",
      "Avoiding citations."
    ],
    answer: 1
  }
];

function saveState() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  updateDashboard();
  updatePreview();
}

function showPage(id) {
  document.querySelectorAll(".page").forEach(page => page.classList.remove("active"));
  document.getElementById(id).classList.add("active");
  window.scrollTo({ top: 0, behavior: "smooth" });
}

function setupNavigation() {
  document.querySelectorAll(".nav-btn").forEach(btn => {
    btn.addEventListener("click", () => showPage(btn.dataset.target));
  });
}

function buildSurvey(formId, type) {
  const form = document.getElementById(formId);
  form.innerHTML = "";

  surveyConfig.forEach((section, sIndex) => {
    const card = document.createElement("div");
    card.className = "card form-card";

    card.innerHTML = `
      <h3>${section.title}</h3>
      <p><em>Scale: 1 = Strongly Disagree, 2 = Disagree, 3 = Neutral, 4 = Agree, 5 = Strongly Agree</em></p>
    `;

    section.items.forEach((item, iIndex) => {
      const row = document.createElement("div");
      row.className = "scale-item";

      row.innerHTML = `
        <p><strong>${item}</strong></p>
        <div class="radio-row">
          <label><input type="radio" name="${type}_${sIndex}_${iIndex}" value="1" required> 1</label>
          <label><input type="radio" name="${type}_${sIndex}_${iIndex}" value="2"> 2</label>
          <label><input type="radio" name="${type}_${sIndex}_${iIndex}" value="3"> 3</label>
          <label><input type="radio" name="${type}_${sIndex}_${iIndex}" value="4"> 4</label>
          <label><input type="radio" name="${type}_${sIndex}_${iIndex}" value="5"> 5</label>
        </div>
      `;

      card.appendChild(row);
    });

    form.appendChild(card);
  });

  const button = document.createElement("button");
  button.className = "primary";
  button.type = "submit";
  button.textContent = type === "pretest" ? "Submit Pre-Test" : "Submit Post-Test";

  form.appendChild(button);

  form.addEventListener("submit", function (e) {
    e.preventDefault();

    const responses = {};
    const variableMeans = {};

    surveyConfig.forEach((section, sIndex) => {
      let total = 0;

      section.items.forEach((item, iIndex) => {
        const selected = form.querySelector(`input[name="${type}_${sIndex}_${iIndex}"]:checked`);
        const value = Number(selected.value);

        responses[`${section.title} - Item ${iIndex + 1}`] = value;
        total += value;
      });

      variableMeans[section.title] = Number((total / section.items.length).toFixed(2));
    });

    state[type] = {
      responses,
      variableMeans,
      submittedAt: new Date().toISOString()
    };

    saveState();

    alert(`${type === "pretest" ? "Pre-Test" : "Post-Test"} saved successfully.`);
    showPage("dashboard");
  });
}

function renderTools() {
  const container = document.getElementById("toolsContainer");
  container.innerHTML = "";

  aiTools.forEach(tool => {
    const explored = state.exploredTools.includes(tool.id);

    const card = document.createElement("div");
    card.className = "tool-card";

    card.innerHTML = `
      <h3>${tool.name}</h3>
      <p><strong>${tool.category}</strong></p>
      <p>${tool.description}</p>
      <div class="tool-tags">
        <span class="tag">AI Tool</span>
        <span class="tag">Learning Support</span>
      </div>
      <button class="${explored ? "secondary" : "primary"}" data-id="${tool.id}" ${explored ? "disabled" : ""}>
        ${explored ? "Explored" : "Mark as Explored"}
      </button>
    `;

    container.appendChild(card);
  });

  container.querySelectorAll("button[data-id]").forEach(btn => {
    btn.addEventListener("click", () => {
      const id = btn.dataset.id;

      if (!state.exploredTools.includes(id)) {
        state.exploredTools.push(id);
      }

      saveState();
      renderTools();
    });
  });
}

function generateRecommendation() {
  const task = document.getElementById("taskType").value;
  const style = document.getElementById("learningStyle").value;
  const resultBox = document.getElementById("recommendationResult");

  if (!task || !style) {
    resultBox.classList.remove("hidden");
    resultBox.innerHTML = `<p class="bad"><strong>Please complete all fields first.</strong></p>`;
    return;
  }

  const recommendation = recommendationMap[task];

  let learningAdvice = "";

  if (style === "simple") {
    learningAdvice = "Use prompts requesting simple explanations, examples, and step-by-step answers.";
  } else if (style === "visual") {
    learningAdvice = "Use tools that support diagrams, slides, images, and visual presentation.";
  } else if (style === "interactive") {
    learningAdvice = "Use conversational AI tools where you can ask follow-up questions.";
  } else if (style === "technical") {
    learningAdvice = "Use detailed prompts requesting technical explanations and structured outputs.";
  }

  resultBox.classList.remove("hidden");

  resultBox.innerHTML = `
    <div class="recommend-card">
      <h3>Recommended AI Tools</h3>
      <p><strong>Suggested Tools:</strong> ${recommendation.tools.join(", ")}</p>
      <p><strong>Why these tools?</strong> ${recommendation.reason}</p>
      <p><strong>Recommendation Strategy:</strong> ${learningAdvice}</p>
      <p><strong>Responsible AI Reminder:</strong> Always verify AI-generated content, check accuracy, and avoid submitting raw AI outputs without review and revision.</p>
    </div>
  `;

  state.recommendation = {
    task,
    learningStyle: style,
    recommendedTools: recommendation.tools,
    reason: recommendation.reason,
    strategy: learningAdvice,
    dateGenerated: new Date().toISOString()
  };

  saveState();
}

function renderQuiz() {
  const container = document.getElementById("quizContainer");
  container.innerHTML = "";

  quizQuestions.forEach((item, index) => {
    const card = document.createElement("div");
    card.className = "card";

    card.innerHTML = `
      <h3>Question ${index + 1}</h3>
      <p>${item.question}</p>
      <div class="radio-row">
        ${item.options.map((opt, optIndex) => `
          <label>
            <input type="radio" name="quiz_${index}" value="${optIndex}">
            ${opt}
          </label>
        `).join("")}
      </div>
    `;

    container.appendChild(card);
  });
}

function gradeQuiz() {
  let score = 0;

  quizQuestions.forEach((q, index) => {
    const checked = document.querySelector(`input[name="quiz_${index}"]:checked`);

    if (checked && Number(checked.value) === q.answer) {
      score++;
    }
  });

  const result = document.getElementById("quizResult");
  result.classList.remove("hidden");

  result.innerHTML = `
    <p class="score good">${score}/${quizQuestions.length}</p>
    <p>You completed the AI literacy self-test.</p>
  `;

  state.quiz = {
    score,
    total: quizQuestions.length,
    completedAt: new Date().toISOString()
  };

  saveState();
}

function checkPrompt() {
  const input = document.getElementById("promptInput").value;
  const result = document.getElementById("promptResult");

  result.classList.remove("hidden");

  if (input.trim().length < 30) {
    result.innerHTML = `<p class="bad"><strong>Your prompt needs more detail and specificity.</strong></p>`;
  } else {
    result.innerHTML = `<p class="good"><strong>Your prompt is reasonably detailed and specific.</strong></p>`;
  }

  state.promptPractice = {
    prompt: input,
    completedAt: new Date().toISOString()
  };

  saveState();
}

function updateDashboard() {
  const checks = {
    pre: !!state.pretest,
    tools: state.exploredTools.length >= 3,
    recommend: !!state.recommendation,
    quiz: !!state.quiz,
    practice: !!state.promptPractice,
    post: !!state.posttest
  };

  document.getElementById("donePre").checked = checks.pre;
  document.getElementById("doneTools").checked = checks.tools;
  document.getElementById("doneRecommend").checked = checks.recommend;
  document.getElementById("doneQuiz").checked = checks.quiz;
  document.getElementById("donePractice").checked = checks.practice;
  document.getElementById("donePost").checked = checks.post;

  const complete = Object.values(checks).filter(Boolean).length;
  const percent = Math.round((complete / 6) * 100);

  document.getElementById("progressFill").style.width = `${percent}%`;
  document.getElementById("progressText").textContent = `${percent}% complete`;
}

function updatePreview() {
  document.getElementById("dataPreview").textContent = JSON.stringify(state, null, 2);
}

function bindButtons() {
  document.getElementById("generateRecommendation").addEventListener("click", generateRecommendation);
  document.getElementById("submitQuiz").addEventListener("click", gradeQuiz);
  document.getElementById("checkPrompt").addEventListener("click", checkPrompt);

  document.getElementById("downloadJson").addEventListener("click", () => {
    const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");

    a.href = url;
    a.download = "ai-learning-tool-data.json";
    a.click();

    URL.revokeObjectURL(url);
  });

  document.getElementById("resetData").addEventListener("click", () => {
    const confirmReset = confirm("Reset all saved data?");
    if (!confirmReset) return;

    localStorage.removeItem(STORAGE_KEY);
    location.reload();
  });
}

document.addEventListener("DOMContentLoaded", () => {
  setupNavigation();
  buildSurvey("pretestForm", "pretest");
  buildSurvey("posttestForm", "posttest");
  renderTools();
  renderQuiz();
  bindButtons();
  updateDashboard();
  updatePreview();
});
